-- Relevant Prosody configuration fragments for meet.example.com.
-- Merge these settings into the configuration generated by Jitsi Meet.
--
-- Install the custom module as:
--   /usr/local/lib/prosody/modules/mod_token_roles.lua
--
-- Keep both the local custom-module directory and the Jitsi package
-- plugin directory in the effective plugin search path.

plugin_paths = {
    "/usr/local/lib/prosody/modules";
    "/usr/share/jitsi-meet/prosody-plugins/";
}

VirtualHost "meet.example.com"
    authentication = "token"

    -- These values must match /etc/jitsi-invite/jwt.env.
    app_id = "replace-me"
    app_secret = "replace-with-a-long-random-secret"

    -- Strict mode:
    --   * do not configure allow_empty_token;
    --   * do not add an anonymous guest VirtualHost.

Component "conference.meet.example.com" "muc"
    restrict_room_creation = true
    storage = "memory"

    modules_enabled = {
        -- Preserve the modules required by the installed Jitsi version.
        "muc_hide_all";
        "muc_meeting_id";
        "muc_domain_mapper";
        "polls";

        -- JWT validation and explicit moderator/guest role enforcement.
        "token_verification";
        "token_roles";

        "muc_rate_limit";
        "muc_password_whitelist";
    }

    admins = {
        "focus@auth.meet.example.com";
    }

    muc_password_whitelist = {
        "focus@auth.meet.example.com";
    }

    muc_room_locking = false
